ifndef COLORPAIR_NUMBERCONVERSIONS_H
#define COLORPAIR_NUMBERCONVERSIONS_H

/*type definitions*/

enum MajorColor {WHITE, RED, BLACK, YELLOW, VIOLET};
enum MinorColor {BLUE, ORANGE, GREEN, BROWN, SLATE};

#endif /*COLORPAIR_NUMBERCONVERSIONS_H*/
